version: "3.7"

services:
    database_ignite:
        image: postgres
        container_name: database_ignite
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=ignite
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=rental_club
        volumes:
            - pgdata:/data/postgres
       

    app:
        build: .
        container_name: rental_club
        restart: always
        ports:
            - 3333:3333
            - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database_ignite
        depends_on:
            - database_ignite
volumes:
    pgdata:
        driver: local